### ISSUE TITLE
Wrong font in new tabs

### ISSUE THREAD

**Issue by Kebap** [demonnic/EMCO#19]
#### Brief summary of issue / Description of requested feature:
Why does EMCO use a different font in tabs at first?

#### Steps to reproduce the issue / Reasons for adding feature:

1. Code like:
```lua
local EMCO = require("MorgenGrauen.demonnic.emco")
function test()
    local tab_active_style = [[
        border-color: rgba(113, 75, 50, 100%);
        border-width: 1px; border-style: solid; border-radius: 8px;
        background-color: rgba(201, 180, 123, 100%);
    ]]
    local tab_inactive_style = [[
        border-color: rgba(113, 75, 50, 100%);
        border-width: 1px; border-style: solid; border-radius: 8px;
        background-color:rgba(200, 200, 160, 20%);
    ]]
    TestEMCO =
        EMCO:new({
            name = "TestEMCO",
            x = "17", y = "23",
            width = "400",
            height = "200",
            gap = 5,
            consoleColor = "black",
            consoles = {
                "Alles",
                "Ebenen",
                "Mitteilungen",
                "Debug"
            },
            allTab = true,
            allTabName = "Alles",
            allTabExclusions = { "Debug" },
            mapTab = false,
            activeTabFGColor = "black",
            activeTabCSS = tab_active_style,
            inactiveTabCSS = tab_inactive_style,
            preserveBackground = true,
            blink = false
    })
end
```

2. Here is immediately after creation:
![image](https://user-images.githubusercontent.com/117238/222931325-bac59089-d060-4303-9d6c-1decaabd9807.png)

3. Here is after clicking each tab once:
![image](https://user-images.githubusercontent.com/117238/222931327-f8a3cb19-0e09-4ebb-b9de-9d8369428867.png)

#### Error output / Expected result of feature
All 3 tabs to the right side show a wrong font at first, whereas picture 2 should be like 3 and not different at all, at all

#### Extra information, such as the Mudlet version, operating system and ideas for how to solve / implement:
Noted in most current PTB

**Comment by demonnic** [comment]
Ok, so I'm not entirely sure -why- the tab font seems to shrink when you click on it, but I -have- figured out a way to force it to be consistent. Will get a release out this weekend with the fix

**Comment by demonnic** [comment]
Fixed in MDK and EMCO reference package as of this weekend.

**Comment by Kebap** [comment]
I am still seeing this in packages created by Github workflow like:

```yml
      - name: Muddle
        uses: demonnic/build-with-muddler@main
        with:
          muddlerVersion: LATEST
```

For example here: https://github.com/MorgenGrauen/mg-mudlet/actions/runs/4443008768

Maybe I am doing it wrong?

**Comment by Kebap** [comment]
My bad, this is not about Muddler at all.
I need to still download the new EMCO version and store it in my repo, so the Lua can require it later.
Not sure if I could teach Muddler to do that for me on each release automatically as well?

**Comment by Kebap** [comment]
Yep, that seemed to do the trick. Thanks for fixing this bug! 👍
